#!/bin/bash

set -e

DEFAULT_CNT="rpi-minidlna"

CMD=$1
CNT=$2

if [ -z "$CMD" ]; then
    echo "Please specify a command (start|stop|status|build|clean)."
    exit 1
fi

if [ -z "$CNT" ]; then
    CNT=$DEFAULT_CNT
fi

CMD_START="docker run -d --net=host -v /mnt/media:/data/media $CNT"
CMD_STOP="docker stop $(docker ps -aq --filter=[name=$CNT])"
CMD_STATUS="docker ps"

CMD_BUILD="docker build -t $CNT-build ./build"
CMD_BUILD_RUN="docker run --rm=true -v $(pwd)/dist/bin:/build $CNT-build"
CMD_BUILD_DIST="docker build -t $CNT ./dist"
CMD_CLEAN="docker rm -f $CNT-build"
CMD_CLEAN_IMG="docker rmi $CNT-build"

case "$CMD" in
    start )
        $CMD_START ;;
    stop )
        $CMD_STOP ;;
    build )
        mkdir -p $(pwd)/dist/bin && \
        $CMD_BUILD && \
        $CMD_BUILD_RUN && \
        $CMD_BUILD_DIST ;;
    clean )
        $CMD_CLEAN 2> /dev/null ; \
        $CMD_CLEAN_IMG ;;
    status )
        $CMD_STATUS | grep $CNT || echo "Not running" ;;
esac
